language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - REACT_APP_API_BASE_URL=http://localhost:8080
    - PACT_BROKER_BASE_URL=https://danjordan.pactflow.io
    # PACT_BROKER_TOKEN is encrypted below
    - secure: "nrTElTJhgSoN3XMqqz2UhcvdZCi++M8Uk6F9AEiO65DDolafptpD+R2DHwn643iwErArAoQwp3T1PHO0tVj9oQbh1Oa6fWQynFr6AFlLSsnvYTmCjuep7/qa3rmTPevCjJfaLEBwM4F/0K9iWj41WNj83L5MZ3pyJSVX3hBovhZeh1BHgaSHcojBqE9naYl37qMa42IgN+2pMi/xy2j0Jbz4OT6t6soS8WlboeaEiYzy2s9muF5oyGuGA9V6q6mBd6C/DamhSAOr38kEf4x6EIYYV//00u8yby3BqrN8cjTL2HytIxV5uFzWayhfqfrPFLloGCNGYR/U+FxMXYmestHQJ+sE7apJy+rGAHYxJDELoUlJ1kUXaXZpwlBDdbH+dein/5Gspo9dzYl1YAdRJi1VC31CZYtZRe8dEU5VENzFvxw5ofiofxOl6OfL2RESXyxZsTCN4sPhlS8yyZhhd5KGR9NbB5QUGbTjZKBb4AyeB7yKs4HNtBnpGtQUzEEAwM4S3qHB2TVfHT51qrJLGnSrZT/YSAaqtrzFqM+hZSUAHi1srK49DxCohbEHLy52Ag9LbZwTgBrGWmbFBThDboBuwmBPOx7nhWJ//oxHb1AUo7+jvxCzAcJuzkF5j/Y/ApB49xPn21Mj66HWwIJ2gChHtvjpDmUu375yRMjLHYQ="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  - make ci
